// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registry/ingest/ingest.proto

package dev.speakeasyapi.schemas;

public final class Ingest {
  private Ingest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IngestRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ingest.IngestRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * har is string containing a HTTP Archive 1.2 formatted file contents
     * </pre>
     *
     * <code>string har = 1;</code>
     * @return The har.
     */
    java.lang.String getHar();
    /**
     * <pre>
     * har is string containing a HTTP Archive 1.2 formatted file contents
     * </pre>
     *
     * <code>string har = 1;</code>
     * @return The bytes for har.
     */
    com.google.protobuf.ByteString
        getHarBytes();

    /**
     * <pre>
     * path_hint is a hint to the ingest service about the structure of the request path
     * </pre>
     *
     * <code>string path_hint = 2;</code>
     * @return The pathHint.
     */
    java.lang.String getPathHint();
    /**
     * <pre>
     * path_hint is a hint to the ingest service about the structure of the request path
     * </pre>
     *
     * <code>string path_hint = 2;</code>
     * @return The bytes for pathHint.
     */
    com.google.protobuf.ByteString
        getPathHintBytes();

    /**
     * <pre>
     * api_id is used to associate requests with a particular Api in the Speakeasy platform
     * </pre>
     *
     * <code>string api_id = 3;</code>
     * @return The apiId.
     */
    java.lang.String getApiId();
    /**
     * <pre>
     * api_id is used to associate requests with a particular Api in the Speakeasy platform
     * </pre>
     *
     * <code>string api_id = 3;</code>
     * @return The bytes for apiId.
     */
    com.google.protobuf.ByteString
        getApiIdBytes();

    /**
     * <pre>
     * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
     * </pre>
     *
     * <code>string version_id = 4;</code>
     * @return The versionId.
     */
    java.lang.String getVersionId();
    /**
     * <pre>
     * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
     * </pre>
     *
     * <code>string version_id = 4;</code>
     * @return The bytes for versionId.
     */
    com.google.protobuf.ByteString
        getVersionIdBytes();

    /**
     * <pre>
     * customer_id is the id of the customer who is making the request
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The customerId.
     */
    java.lang.String getCustomerId();
    /**
     * <pre>
     * customer_id is the id of the customer who is making the request
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The bytes for customerId.
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();
  }
  /**
   * <pre>
   * IngestRequest is the request message for the ingest rpc.
   * </pre>
   *
   * Protobuf type {@code ingest.IngestRequest}
   */
  public static final class IngestRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ingest.IngestRequest)
      IngestRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IngestRequest.newBuilder() to construct.
    private IngestRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IngestRequest() {
      har_ = "";
      pathHint_ = "";
      apiId_ = "";
      versionId_ = "";
      customerId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IngestRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IngestRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              har_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pathHint_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              apiId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              versionId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              customerId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.speakeasyapi.schemas.Ingest.IngestRequest.class, dev.speakeasyapi.schemas.Ingest.IngestRequest.Builder.class);
    }

    public static final int HAR_FIELD_NUMBER = 1;
    private volatile java.lang.Object har_;
    /**
     * <pre>
     * har is string containing a HTTP Archive 1.2 formatted file contents
     * </pre>
     *
     * <code>string har = 1;</code>
     * @return The har.
     */
    @java.lang.Override
    public java.lang.String getHar() {
      java.lang.Object ref = har_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        har_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * har is string containing a HTTP Archive 1.2 formatted file contents
     * </pre>
     *
     * <code>string har = 1;</code>
     * @return The bytes for har.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHarBytes() {
      java.lang.Object ref = har_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        har_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_HINT_FIELD_NUMBER = 2;
    private volatile java.lang.Object pathHint_;
    /**
     * <pre>
     * path_hint is a hint to the ingest service about the structure of the request path
     * </pre>
     *
     * <code>string path_hint = 2;</code>
     * @return The pathHint.
     */
    @java.lang.Override
    public java.lang.String getPathHint() {
      java.lang.Object ref = pathHint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathHint_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * path_hint is a hint to the ingest service about the structure of the request path
     * </pre>
     *
     * <code>string path_hint = 2;</code>
     * @return The bytes for pathHint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathHintBytes() {
      java.lang.Object ref = pathHint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathHint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int API_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object apiId_;
    /**
     * <pre>
     * api_id is used to associate requests with a particular Api in the Speakeasy platform
     * </pre>
     *
     * <code>string api_id = 3;</code>
     * @return The apiId.
     */
    @java.lang.Override
    public java.lang.String getApiId() {
      java.lang.Object ref = apiId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * api_id is used to associate requests with a particular Api in the Speakeasy platform
     * </pre>
     *
     * <code>string api_id = 3;</code>
     * @return The bytes for apiId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApiIdBytes() {
      java.lang.Object ref = apiId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object versionId_;
    /**
     * <pre>
     * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
     * </pre>
     *
     * <code>string version_id = 4;</code>
     * @return The versionId.
     */
    @java.lang.Override
    public java.lang.String getVersionId() {
      java.lang.Object ref = versionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        versionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
     * </pre>
     *
     * <code>string version_id = 4;</code>
     * @return The bytes for versionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionIdBytes() {
      java.lang.Object ref = versionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object customerId_;
    /**
     * <pre>
     * customer_id is the id of the customer who is making the request
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * customer_id is the id of the customer who is making the request
     * </pre>
     *
     * <code>string customer_id = 5;</code>
     * @return The bytes for customerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(har_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, har_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pathHint_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pathHint_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(apiId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, apiId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(versionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, versionId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, customerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(har_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, har_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pathHint_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pathHint_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(apiId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, apiId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(versionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, versionId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, customerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.speakeasyapi.schemas.Ingest.IngestRequest)) {
        return super.equals(obj);
      }
      dev.speakeasyapi.schemas.Ingest.IngestRequest other = (dev.speakeasyapi.schemas.Ingest.IngestRequest) obj;

      if (!getHar()
          .equals(other.getHar())) return false;
      if (!getPathHint()
          .equals(other.getPathHint())) return false;
      if (!getApiId()
          .equals(other.getApiId())) return false;
      if (!getVersionId()
          .equals(other.getVersionId())) return false;
      if (!getCustomerId()
          .equals(other.getCustomerId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HAR_FIELD_NUMBER;
      hash = (53 * hash) + getHar().hashCode();
      hash = (37 * hash) + PATH_HINT_FIELD_NUMBER;
      hash = (53 * hash) + getPathHint().hashCode();
      hash = (37 * hash) + API_ID_FIELD_NUMBER;
      hash = (53 * hash) + getApiId().hashCode();
      hash = (37 * hash) + VERSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getVersionId().hashCode();
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.speakeasyapi.schemas.Ingest.IngestRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IngestRequest is the request message for the ingest rpc.
     * </pre>
     *
     * Protobuf type {@code ingest.IngestRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ingest.IngestRequest)
        dev.speakeasyapi.schemas.Ingest.IngestRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.speakeasyapi.schemas.Ingest.IngestRequest.class, dev.speakeasyapi.schemas.Ingest.IngestRequest.Builder.class);
      }

      // Construct using dev.speakeasyapi.schemas.Ingest.IngestRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        har_ = "";

        pathHint_ = "";

        apiId_ = "";

        versionId_ = "";

        customerId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestRequest_descriptor;
      }

      @java.lang.Override
      public dev.speakeasyapi.schemas.Ingest.IngestRequest getDefaultInstanceForType() {
        return dev.speakeasyapi.schemas.Ingest.IngestRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.speakeasyapi.schemas.Ingest.IngestRequest build() {
        dev.speakeasyapi.schemas.Ingest.IngestRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.speakeasyapi.schemas.Ingest.IngestRequest buildPartial() {
        dev.speakeasyapi.schemas.Ingest.IngestRequest result = new dev.speakeasyapi.schemas.Ingest.IngestRequest(this);
        result.har_ = har_;
        result.pathHint_ = pathHint_;
        result.apiId_ = apiId_;
        result.versionId_ = versionId_;
        result.customerId_ = customerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.speakeasyapi.schemas.Ingest.IngestRequest) {
          return mergeFrom((dev.speakeasyapi.schemas.Ingest.IngestRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.speakeasyapi.schemas.Ingest.IngestRequest other) {
        if (other == dev.speakeasyapi.schemas.Ingest.IngestRequest.getDefaultInstance()) return this;
        if (!other.getHar().isEmpty()) {
          har_ = other.har_;
          onChanged();
        }
        if (!other.getPathHint().isEmpty()) {
          pathHint_ = other.pathHint_;
          onChanged();
        }
        if (!other.getApiId().isEmpty()) {
          apiId_ = other.apiId_;
          onChanged();
        }
        if (!other.getVersionId().isEmpty()) {
          versionId_ = other.versionId_;
          onChanged();
        }
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.speakeasyapi.schemas.Ingest.IngestRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.speakeasyapi.schemas.Ingest.IngestRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object har_ = "";
      /**
       * <pre>
       * har is string containing a HTTP Archive 1.2 formatted file contents
       * </pre>
       *
       * <code>string har = 1;</code>
       * @return The har.
       */
      public java.lang.String getHar() {
        java.lang.Object ref = har_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          har_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * har is string containing a HTTP Archive 1.2 formatted file contents
       * </pre>
       *
       * <code>string har = 1;</code>
       * @return The bytes for har.
       */
      public com.google.protobuf.ByteString
          getHarBytes() {
        java.lang.Object ref = har_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          har_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * har is string containing a HTTP Archive 1.2 formatted file contents
       * </pre>
       *
       * <code>string har = 1;</code>
       * @param value The har to set.
       * @return This builder for chaining.
       */
      public Builder setHar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        har_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * har is string containing a HTTP Archive 1.2 formatted file contents
       * </pre>
       *
       * <code>string har = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHar() {
        
        har_ = getDefaultInstance().getHar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * har is string containing a HTTP Archive 1.2 formatted file contents
       * </pre>
       *
       * <code>string har = 1;</code>
       * @param value The bytes for har to set.
       * @return This builder for chaining.
       */
      public Builder setHarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        har_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pathHint_ = "";
      /**
       * <pre>
       * path_hint is a hint to the ingest service about the structure of the request path
       * </pre>
       *
       * <code>string path_hint = 2;</code>
       * @return The pathHint.
       */
      public java.lang.String getPathHint() {
        java.lang.Object ref = pathHint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pathHint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * path_hint is a hint to the ingest service about the structure of the request path
       * </pre>
       *
       * <code>string path_hint = 2;</code>
       * @return The bytes for pathHint.
       */
      public com.google.protobuf.ByteString
          getPathHintBytes() {
        java.lang.Object ref = pathHint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pathHint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * path_hint is a hint to the ingest service about the structure of the request path
       * </pre>
       *
       * <code>string path_hint = 2;</code>
       * @param value The pathHint to set.
       * @return This builder for chaining.
       */
      public Builder setPathHint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pathHint_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * path_hint is a hint to the ingest service about the structure of the request path
       * </pre>
       *
       * <code>string path_hint = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPathHint() {
        
        pathHint_ = getDefaultInstance().getPathHint();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * path_hint is a hint to the ingest service about the structure of the request path
       * </pre>
       *
       * <code>string path_hint = 2;</code>
       * @param value The bytes for pathHint to set.
       * @return This builder for chaining.
       */
      public Builder setPathHintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pathHint_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object apiId_ = "";
      /**
       * <pre>
       * api_id is used to associate requests with a particular Api in the Speakeasy platform
       * </pre>
       *
       * <code>string api_id = 3;</code>
       * @return The apiId.
       */
      public java.lang.String getApiId() {
        java.lang.Object ref = apiId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apiId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * api_id is used to associate requests with a particular Api in the Speakeasy platform
       * </pre>
       *
       * <code>string api_id = 3;</code>
       * @return The bytes for apiId.
       */
      public com.google.protobuf.ByteString
          getApiIdBytes() {
        java.lang.Object ref = apiId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apiId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * api_id is used to associate requests with a particular Api in the Speakeasy platform
       * </pre>
       *
       * <code>string api_id = 3;</code>
       * @param value The apiId to set.
       * @return This builder for chaining.
       */
      public Builder setApiId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apiId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * api_id is used to associate requests with a particular Api in the Speakeasy platform
       * </pre>
       *
       * <code>string api_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearApiId() {
        
        apiId_ = getDefaultInstance().getApiId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * api_id is used to associate requests with a particular Api in the Speakeasy platform
       * </pre>
       *
       * <code>string api_id = 3;</code>
       * @param value The bytes for apiId to set.
       * @return This builder for chaining.
       */
      public Builder setApiIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apiId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object versionId_ = "";
      /**
       * <pre>
       * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
       * </pre>
       *
       * <code>string version_id = 4;</code>
       * @return The versionId.
       */
      public java.lang.String getVersionId() {
        java.lang.Object ref = versionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          versionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
       * </pre>
       *
       * <code>string version_id = 4;</code>
       * @return The bytes for versionId.
       */
      public com.google.protobuf.ByteString
          getVersionIdBytes() {
        java.lang.Object ref = versionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
       * </pre>
       *
       * <code>string version_id = 4;</code>
       * @param value The versionId to set.
       * @return This builder for chaining.
       */
      public Builder setVersionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        versionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
       * </pre>
       *
       * <code>string version_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersionId() {
        
        versionId_ = getDefaultInstance().getVersionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
       * </pre>
       *
       * <code>string version_id = 4;</code>
       * @param value The bytes for versionId to set.
       * @return This builder for chaining.
       */
      public Builder setVersionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        versionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <pre>
       * customer_id is the id of the customer who is making the request
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @return The customerId.
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * customer_id is the id of the customer who is making the request
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @return The bytes for customerId.
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * customer_id is the id of the customer who is making the request
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * customer_id is the id of the customer who is making the request
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * customer_id is the id of the customer who is making the request
       * </pre>
       *
       * <code>string customer_id = 5;</code>
       * @param value The bytes for customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ingest.IngestRequest)
    }

    // @@protoc_insertion_point(class_scope:ingest.IngestRequest)
    private static final dev.speakeasyapi.schemas.Ingest.IngestRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.speakeasyapi.schemas.Ingest.IngestRequest();
    }

    public static dev.speakeasyapi.schemas.Ingest.IngestRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IngestRequest>
        PARSER = new com.google.protobuf.AbstractParser<IngestRequest>() {
      @java.lang.Override
      public IngestRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IngestRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IngestRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IngestRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.speakeasyapi.schemas.Ingest.IngestRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IngestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ingest.IngestResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * IngestResponse is the response message for the ingest rpc.
   * </pre>
   *
   * Protobuf type {@code ingest.IngestResponse}
   */
  public static final class IngestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ingest.IngestResponse)
      IngestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IngestResponse.newBuilder() to construct.
    private IngestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IngestResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IngestResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IngestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.speakeasyapi.schemas.Ingest.IngestResponse.class, dev.speakeasyapi.schemas.Ingest.IngestResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.speakeasyapi.schemas.Ingest.IngestResponse)) {
        return super.equals(obj);
      }
      dev.speakeasyapi.schemas.Ingest.IngestResponse other = (dev.speakeasyapi.schemas.Ingest.IngestResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.schemas.Ingest.IngestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.speakeasyapi.schemas.Ingest.IngestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IngestResponse is the response message for the ingest rpc.
     * </pre>
     *
     * Protobuf type {@code ingest.IngestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ingest.IngestResponse)
        dev.speakeasyapi.schemas.Ingest.IngestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.speakeasyapi.schemas.Ingest.IngestResponse.class, dev.speakeasyapi.schemas.Ingest.IngestResponse.Builder.class);
      }

      // Construct using dev.speakeasyapi.schemas.Ingest.IngestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.speakeasyapi.schemas.Ingest.internal_static_ingest_IngestResponse_descriptor;
      }

      @java.lang.Override
      public dev.speakeasyapi.schemas.Ingest.IngestResponse getDefaultInstanceForType() {
        return dev.speakeasyapi.schemas.Ingest.IngestResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.speakeasyapi.schemas.Ingest.IngestResponse build() {
        dev.speakeasyapi.schemas.Ingest.IngestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.speakeasyapi.schemas.Ingest.IngestResponse buildPartial() {
        dev.speakeasyapi.schemas.Ingest.IngestResponse result = new dev.speakeasyapi.schemas.Ingest.IngestResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.speakeasyapi.schemas.Ingest.IngestResponse) {
          return mergeFrom((dev.speakeasyapi.schemas.Ingest.IngestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.speakeasyapi.schemas.Ingest.IngestResponse other) {
        if (other == dev.speakeasyapi.schemas.Ingest.IngestResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.speakeasyapi.schemas.Ingest.IngestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.speakeasyapi.schemas.Ingest.IngestResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ingest.IngestResponse)
    }

    // @@protoc_insertion_point(class_scope:ingest.IngestResponse)
    private static final dev.speakeasyapi.schemas.Ingest.IngestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.speakeasyapi.schemas.Ingest.IngestResponse();
    }

    public static dev.speakeasyapi.schemas.Ingest.IngestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IngestResponse>
        PARSER = new com.google.protobuf.AbstractParser<IngestResponse>() {
      @java.lang.Override
      public IngestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IngestResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IngestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IngestResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.speakeasyapi.schemas.Ingest.IngestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ingest_IngestRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ingest_IngestRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ingest_IngestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ingest_IngestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034registry/ingest/ingest.proto\022\006ingest\"h" +
      "\n\rIngestRequest\022\013\n\003har\030\001 \001(\t\022\021\n\tpath_hin" +
      "t\030\002 \001(\t\022\016\n\006api_id\030\003 \001(\t\022\022\n\nversion_id\030\004 " +
      "\001(\t\022\023\n\013customer_id\030\005 \001(\t\"\020\n\016IngestRespon" +
      "se2J\n\rIngestService\0229\n\006Ingest\022\025.ingest.I" +
      "ngestRequest\032\026.ingest.IngestResponse\"\000B^" +
      "\n\030dev.speakeasyapi.schemasZBgithub.com/s" +
      "peakeasy-api/speakeasy-schemas/grpc/go/r" +
      "egistry/ingestb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ingest_IngestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ingest_IngestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ingest_IngestRequest_descriptor,
        new java.lang.String[] { "Har", "PathHint", "ApiId", "VersionId", "CustomerId", });
    internal_static_ingest_IngestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ingest_IngestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ingest_IngestResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
