[package]
edition = "2021"
name = "speakeasy-protos"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = {version = "0.11"}
tonic = {version = "0.8", features = ["transport", "prost"]}
