// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: grpc/protos/registry/ingest/ingest.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestRequest is the request message for the ingest rpc.
type IngestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// har is string containing a HTTP Archive 1.2 formatted file contents
	Har string `protobuf:"bytes,1,opt,name=har,proto3" json:"har,omitempty"`
	// path_hint is a hint to the ingest service about the structure of the request path
	PathHint string `protobuf:"bytes,2,opt,name=path_hint,json=pathHint,proto3" json:"path_hint,omitempty"`
	// api_id is used to associate requests with a particular Api in the Speakeasy platform
	ApiId string `protobuf:"bytes,3,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	// version_id is used to associate requests with a particular version of an Api in the Speakeasy platform
	VersionId string `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// customer_id is the id of the customer who is making the request
	CustomerId string `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_registry_ingest_ingest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_registry_ingest_ingest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_registry_ingest_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetHar() string {
	if x != nil {
		return x.Har
	}
	return ""
}

func (x *IngestRequest) GetPathHint() string {
	if x != nil {
		return x.PathHint
	}
	return ""
}

func (x *IngestRequest) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

func (x *IngestRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *IngestRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// IngestResponse is the response message for the ingest rpc.
type IngestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_registry_ingest_ingest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_registry_ingest_ingest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_registry_ingest_ingest_proto_rawDescGZIP(), []int{1}
}

var File_grpc_protos_registry_ingest_ingest_proto protoreflect.FileDescriptor

var file_grpc_protos_registry_ingest_ingest_proto_rawDesc = []byte{
	0x0a, 0x28, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x69, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x68, 0x61, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x68,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x74, 0x68, 0x48,
	0x69, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x69, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4a, 0x0a, 0x0d,
	0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a,
	0x06, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x5e, 0x0a, 0x18, 0x64, 0x65, 0x76, 0x2e,
	0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x61, 0x73, 0x79, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x73, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x61, 0x73, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x70, 0x65, 0x61, 0x6b, 0x65, 0x61, 0x73, 0x79, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_protos_registry_ingest_ingest_proto_rawDescOnce sync.Once
	file_grpc_protos_registry_ingest_ingest_proto_rawDescData = file_grpc_protos_registry_ingest_ingest_proto_rawDesc
)

func file_grpc_protos_registry_ingest_ingest_proto_rawDescGZIP() []byte {
	file_grpc_protos_registry_ingest_ingest_proto_rawDescOnce.Do(func() {
		file_grpc_protos_registry_ingest_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_protos_registry_ingest_ingest_proto_rawDescData)
	})
	return file_grpc_protos_registry_ingest_ingest_proto_rawDescData
}

var file_grpc_protos_registry_ingest_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_protos_registry_ingest_ingest_proto_goTypes = []interface{}{
	(*IngestRequest)(nil),  // 0: ingest.IngestRequest
	(*IngestResponse)(nil), // 1: ingest.IngestResponse
}
var file_grpc_protos_registry_ingest_ingest_proto_depIdxs = []int32{
	0, // 0: ingest.IngestService.Ingest:input_type -> ingest.IngestRequest
	1, // 1: ingest.IngestService.Ingest:output_type -> ingest.IngestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_protos_registry_ingest_ingest_proto_init() }
func file_grpc_protos_registry_ingest_ingest_proto_init() {
	if File_grpc_protos_registry_ingest_ingest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_protos_registry_ingest_ingest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IngestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_registry_ingest_ingest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IngestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_protos_registry_ingest_ingest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protos_registry_ingest_ingest_proto_goTypes,
		DependencyIndexes: file_grpc_protos_registry_ingest_ingest_proto_depIdxs,
		MessageInfos:      file_grpc_protos_registry_ingest_ingest_proto_msgTypes,
	}.Build()
	File_grpc_protos_registry_ingest_ingest_proto = out.File
	file_grpc_protos_registry_ingest_ingest_proto_rawDesc = nil
	file_grpc_protos_registry_ingest_ingest_proto_goTypes = nil
	file_grpc_protos_registry_ingest_ingest_proto_depIdxs = nil
}
