# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: registry/ingest/ingest.proto for package 'ingest'

require 'grpc'
require 'registry/ingest/ingest_pb'

module Ingest
  module IngestService
    # IngestService is the service definition for the registry ingest endpoint.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ingest.IngestService'

      #  Ingest is the rpc handling ingest from the SDK.
      rpc :Ingest, ::Ingest::IngestRequest, ::Ingest::IngestResponse
    end

    Stub = Service.rpc_stub_class
  end
end
