// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registry/embedaccesstoken/embedaccesstoken.proto

package dev.speakeasyapi.accesstokens;

public final class Embedaccesstoken {
  private Embedaccesstoken() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmbedAccessTokenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:embedaccesstoken.EmbedAccessTokenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    java.util.List<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter> 
        getFiltersList();
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter getFilters(int index);
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    int getFiltersCount();
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    java.util.List<? extends dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder> 
        getFiltersOrBuilderList();
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder getFiltersOrBuilder(
        int index);
  }
  /**
   * <pre>
   * EmbedAccessTokenRequest is the request message for the Get rpc.
   * </pre>
   *
   * Protobuf type {@code embedaccesstoken.EmbedAccessTokenRequest}
   */
  public static final class EmbedAccessTokenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:embedaccesstoken.EmbedAccessTokenRequest)
      EmbedAccessTokenRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmbedAccessTokenRequest.newBuilder() to construct.
    private EmbedAccessTokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmbedAccessTokenRequest() {
      filters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EmbedAccessTokenRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmbedAccessTokenRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                filters_ = new java.util.ArrayList<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter>();
                mutable_bitField0_ |= 0x00000001;
              }
              filters_.add(
                  input.readMessage(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          filters_ = java.util.Collections.unmodifiableList(filters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.class, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Builder.class);
    }

    public interface FilterOrBuilder extends
        // @@protoc_insertion_point(interface_extends:embedaccesstoken.EmbedAccessTokenRequest.Filter)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>string operator = 2;</code>
       * @return The operator.
       */
      java.lang.String getOperator();
      /**
       * <code>string operator = 2;</code>
       * @return The bytes for operator.
       */
      com.google.protobuf.ByteString
          getOperatorBytes();

      /**
       * <code>string value = 3;</code>
       * @return The value.
       */
      java.lang.String getValue();
      /**
       * <code>string value = 3;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code embedaccesstoken.EmbedAccessTokenRequest.Filter}
     */
    public static final class Filter extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:embedaccesstoken.EmbedAccessTokenRequest.Filter)
        FilterOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Filter.newBuilder() to construct.
      private Filter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Filter() {
        key_ = "";
        operator_ = "";
        value_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Filter();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Filter(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                key_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                operator_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                value_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.class, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OPERATOR_FIELD_NUMBER = 2;
      private volatile java.lang.Object operator_;
      /**
       * <code>string operator = 2;</code>
       * @return The operator.
       */
      @java.lang.Override
      public java.lang.String getOperator() {
        java.lang.Object ref = operator_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operator_ = s;
          return s;
        }
      }
      /**
       * <code>string operator = 2;</code>
       * @return The bytes for operator.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        java.lang.Object ref = operator_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 3;
      private volatile java.lang.Object value_;
      /**
       * <code>string value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        }
      }
      /**
       * <code>string value = 3;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, operator_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, operator_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter)) {
          return super.equals(obj);
        }
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter other = (dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter) obj;

        if (!getKey()
            .equals(other.getKey())) return false;
        if (!getOperator()
            .equals(other.getOperator())) return false;
        if (!getValue()
            .equals(other.getValue())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + getOperator().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code embedaccesstoken.EmbedAccessTokenRequest.Filter}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:embedaccesstoken.EmbedAccessTokenRequest.Filter)
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.class, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder.class);
        }

        // Construct using dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";

          operator_ = "";

          value_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_descriptor;
        }

        @java.lang.Override
        public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter getDefaultInstanceForType() {
          return dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.getDefaultInstance();
        }

        @java.lang.Override
        public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter build() {
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter buildPartial() {
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter result = new dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter(this);
          result.key_ = key_;
          result.operator_ = operator_;
          result.value_ = value_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter) {
            return mergeFrom((dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter other) {
          if (other == dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            onChanged();
          }
          if (!other.getOperator().isEmpty()) {
            operator_ = other.operator_;
            onChanged();
          }
          if (!other.getValue().isEmpty()) {
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 1;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object operator_ = "";
        /**
         * <code>string operator = 2;</code>
         * @return The operator.
         */
        public java.lang.String getOperator() {
          java.lang.Object ref = operator_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            operator_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string operator = 2;</code>
         * @return The bytes for operator.
         */
        public com.google.protobuf.ByteString
            getOperatorBytes() {
          java.lang.Object ref = operator_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            operator_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string operator = 2;</code>
         * @param value The operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperator(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          operator_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string operator = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearOperator() {
          
          operator_ = getDefaultInstance().getOperator();
          onChanged();
          return this;
        }
        /**
         * <code>string operator = 2;</code>
         * @param value The bytes for operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperatorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          operator_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>string value = 3;</code>
         * @return The value.
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string value = 3;</code>
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string value = 3;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string value = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>string value = 3;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          value_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:embedaccesstoken.EmbedAccessTokenRequest.Filter)
      }

      // @@protoc_insertion_point(class_scope:embedaccesstoken.EmbedAccessTokenRequest.Filter)
      private static final dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter();
      }

      public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Filter>
          PARSER = new com.google.protobuf.AbstractParser<Filter>() {
        @java.lang.Override
        public Filter parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Filter(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Filter> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Filter> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FILTERS_FIELD_NUMBER = 1;
    private java.util.List<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter> filters_;
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    @java.lang.Override
    public java.util.List<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter> getFiltersList() {
      return filters_;
    }
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder> 
        getFiltersOrBuilderList() {
      return filters_;
    }
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    @java.lang.Override
    public int getFiltersCount() {
      return filters_.size();
    }
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    @java.lang.Override
    public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter getFilters(int index) {
      return filters_.get(index);
    }
    /**
     * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
     */
    @java.lang.Override
    public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder getFiltersOrBuilder(
        int index) {
      return filters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < filters_.size(); i++) {
        output.writeMessage(1, filters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < filters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, filters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest)) {
        return super.equals(obj);
      }
      dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest other = (dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest) obj;

      if (!getFiltersList()
          .equals(other.getFiltersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFiltersCount() > 0) {
        hash = (37 * hash) + FILTERS_FIELD_NUMBER;
        hash = (53 * hash) + getFiltersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * EmbedAccessTokenRequest is the request message for the Get rpc.
     * </pre>
     *
     * Protobuf type {@code embedaccesstoken.EmbedAccessTokenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:embedaccesstoken.EmbedAccessTokenRequest)
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.class, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Builder.class);
      }

      // Construct using dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFiltersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor;
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest getDefaultInstanceForType() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest build() {
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest buildPartial() {
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest result = new dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest(this);
        int from_bitField0_ = bitField0_;
        if (filtersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            filters_ = java.util.Collections.unmodifiableList(filters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.filters_ = filters_;
        } else {
          result.filters_ = filtersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest) {
          return mergeFrom((dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest other) {
        if (other == dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.getDefaultInstance()) return this;
        if (filtersBuilder_ == null) {
          if (!other.filters_.isEmpty()) {
            if (filters_.isEmpty()) {
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFiltersIsMutable();
              filters_.addAll(other.filters_);
            }
            onChanged();
          }
        } else {
          if (!other.filters_.isEmpty()) {
            if (filtersBuilder_.isEmpty()) {
              filtersBuilder_.dispose();
              filtersBuilder_ = null;
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filtersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFiltersFieldBuilder() : null;
            } else {
              filtersBuilder_.addAllMessages(other.filters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter> filters_ =
        java.util.Collections.emptyList();
      private void ensureFiltersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          filters_ = new java.util.ArrayList<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter>(filters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder> filtersBuilder_;

      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public java.util.List<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter> getFiltersList() {
        if (filtersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filters_);
        } else {
          return filtersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public int getFiltersCount() {
        if (filtersBuilder_ == null) {
          return filters_.size();
        } else {
          return filtersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter getFilters(int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);
        } else {
          return filtersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder setFilters(
          int index, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.set(index, value);
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder setFilters(
          int index, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.set(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder addFilters(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder addFilters(
          int index, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(index, value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder addFilters(
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder addFilters(
          int index, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder addAllFilters(
          java.lang.Iterable<? extends dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter> values) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, filters_);
          onChanged();
        } else {
          filtersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder clearFilters() {
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public Builder removeFilters(int index) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.remove(index);
          onChanged();
        } else {
          filtersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder getFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder getFiltersOrBuilder(
          int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);  } else {
          return filtersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public java.util.List<? extends dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder> 
           getFiltersOrBuilderList() {
        if (filtersBuilder_ != null) {
          return filtersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filters_);
        }
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder addFiltersBuilder() {
        return getFiltersFieldBuilder().addBuilder(
            dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.getDefaultInstance());
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder addFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().addBuilder(
            index, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.getDefaultInstance());
      }
      /**
       * <code>repeated .embedaccesstoken.EmbedAccessTokenRequest.Filter filters = 1;</code>
       */
      public java.util.List<dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder> 
           getFiltersBuilderList() {
        return getFiltersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder> 
          getFiltersFieldBuilder() {
        if (filtersBuilder_ == null) {
          filtersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.Filter.Builder, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest.FilterOrBuilder>(
                  filters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          filters_ = null;
        }
        return filtersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:embedaccesstoken.EmbedAccessTokenRequest)
    }

    // @@protoc_insertion_point(class_scope:embedaccesstoken.EmbedAccessTokenRequest)
    private static final dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest();
    }

    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmbedAccessTokenRequest>
        PARSER = new com.google.protobuf.AbstractParser<EmbedAccessTokenRequest>() {
      @java.lang.Override
      public EmbedAccessTokenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmbedAccessTokenRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmbedAccessTokenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmbedAccessTokenRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmbedAccessTokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:embedaccesstoken.EmbedAccessTokenResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string accessToken = 1;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <code>string accessToken = 1;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();
  }
  /**
   * <pre>
   * EmbedAccessTokenResponse is the response message for the Get rpc.
   * </pre>
   *
   * Protobuf type {@code embedaccesstoken.EmbedAccessTokenResponse}
   */
  public static final class EmbedAccessTokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:embedaccesstoken.EmbedAccessTokenResponse)
      EmbedAccessTokenResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmbedAccessTokenResponse.newBuilder() to construct.
    private EmbedAccessTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmbedAccessTokenResponse() {
      accessToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EmbedAccessTokenResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmbedAccessTokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.class, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.Builder.class);
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string accessToken = 1;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string accessToken = 1;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse)) {
        return super.equals(obj);
      }
      dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse other = (dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse) obj;

      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * EmbedAccessTokenResponse is the response message for the Get rpc.
     * </pre>
     *
     * Protobuf type {@code embedaccesstoken.EmbedAccessTokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:embedaccesstoken.EmbedAccessTokenResponse)
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.class, dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.Builder.class);
      }

      // Construct using dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accessToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.internal_static_embedaccesstoken_EmbedAccessTokenResponse_descriptor;
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse getDefaultInstanceForType() {
        return dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse build() {
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse buildPartial() {
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse result = new dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse(this);
        result.accessToken_ = accessToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse) {
          return mergeFrom((dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse other) {
        if (other == dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse.getDefaultInstance()) return this;
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string accessToken = 1;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accessToken = 1;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessToken = 1;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 1;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:embedaccesstoken.EmbedAccessTokenResponse)
    }

    // @@protoc_insertion_point(class_scope:embedaccesstoken.EmbedAccessTokenResponse)
    private static final dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse();
    }

    public static dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmbedAccessTokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<EmbedAccessTokenResponse>() {
      @java.lang.Override
      public EmbedAccessTokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmbedAccessTokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmbedAccessTokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmbedAccessTokenResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.speakeasyapi.accesstokens.Embedaccesstoken.EmbedAccessTokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_embedaccesstoken_EmbedAccessTokenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_embedaccesstoken_EmbedAccessTokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_embedaccesstoken_EmbedAccessTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0registry/embedaccesstoken/embedaccesst" +
      "oken.proto\022\020embedaccesstoken\"\224\001\n\027EmbedAc" +
      "cessTokenRequest\022A\n\007filters\030\001 \003(\01320.embe" +
      "daccesstoken.EmbedAccessTokenRequest.Fil" +
      "ter\0326\n\006Filter\022\013\n\003key\030\001 \001(\t\022\020\n\010operator\030\002" +
      " \001(\t\022\r\n\005value\030\003 \001(\t\"/\n\030EmbedAccessTokenR" +
      "esponse\022\023\n\013accessToken\030\001 \001(\t2y\n\027EmbedAcc" +
      "essTokenService\022^\n\003Get\022).embedaccesstoke" +
      "n.EmbedAccessTokenRequest\032*.embedaccesst" +
      "oken.EmbedAccessTokenResponse\"\000Bm\n\035dev.s" +
      "peakeasyapi.accesstokensZLgithub.com/spe" +
      "akeasy-api/speakeasy-schemas/grpc/go/reg" +
      "istry/embedaccesstokenb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_embedaccesstoken_EmbedAccessTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor,
        new java.lang.String[] { "Filters", });
    internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_descriptor =
      internal_static_embedaccesstoken_EmbedAccessTokenRequest_descriptor.getNestedTypes().get(0);
    internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_embedaccesstoken_EmbedAccessTokenRequest_Filter_descriptor,
        new java.lang.String[] { "Key", "Operator", "Value", });
    internal_static_embedaccesstoken_EmbedAccessTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_embedaccesstoken_EmbedAccessTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_embedaccesstoken_EmbedAccessTokenResponse_descriptor,
        new java.lang.String[] { "AccessToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
