# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: registry/embedaccesstoken/embedaccesstoken.proto for package 'embedaccesstoken'

require 'grpc'
require 'registry/embedaccesstoken/embedaccesstoken_pb'

module Embedaccesstoken
  module EmbedAccessTokenService
    # EmbedAccessTokenService is the service definition for the registry embed-access-token endpoint.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'embedaccesstoken.EmbedAccessTokenService'

      #  Get is the rpc handling access token retrieval from the SDK
      rpc :Get, ::Embedaccesstoken::EmbedAccessTokenRequest, ::Embedaccesstoken::EmbedAccessTokenResponse
    end

    Stub = Service.rpc_stub_class
  end
end
